---
title: "Create Holiday Regressor"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CreateHolidayRegressor}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This script can be used to create holiday regressors, especially for German Holidays.

```{r functions}
### Convenience function to get the lags of a time series
### Author: Daniel Ollech
lag0 <- function (x, Lag = 1) {
    y <- zoo::na.fill0(stats::lag(x, k = Lag), 0)
    return(y)
}

### Creating daylight saving time regressor
### Author: Jakob Oberhammer
create_dst_regressor <- function (x, spring = TRUE, autumn = FALSE) {
    if (!xts::is.xts(x)) {
        stop("x must an xts object!")
    }
    if (!spring & !autumn) {
        stop("You should set either spring or autumn to TRUE.")
    }
    dates <- zoo::index(x)
    weekDay <- xts::xts(as.numeric(format(dates, "%w")), order.by = dates)
    monthDay <- xts::xts(as.numeric(format(dates, "%d")), order.by = dates)
    month <- xts::xts(as.numeric(format(dates, "%m")), order.by = dates)
    year <- xts::xts(as.numeric(format(dates, "%Y")), order.by = dates)
    dst <- xts::xts(rep(0, length(x)), order.by = dates)
    dst[dates == "1916-04-30"] <- spring
    dst[dates == "1916-10-01"] <- autumn
    dst[dates == "1917-04-16"] <- spring
    dst[dates == "1917-09-17"] <- autumn
    dst[dates == "1918-04-15"] <- spring
    dst[dates == "1918-09-16"] <- autumn
    dst[dates == "1940-04-01"] <- spring
    dst[dates == "1942-11-02"] <- autumn
    dst[dates == "1943-04-06"] <- spring
    dst[dates == "1943-09-28"] <- autumn
    dst[dates == "1944-04-03"] <- spring
    dst[dates == "1944-10-02"] <- autumn
    dst[dates == "1945-04-02"] <- spring
    dst[dates == "1945-09-16"] <- autumn
    dst[dates == "1946-04-14"] <- spring
    dst[dates == "1946-10-07"] <- autumn
    dst[dates == "1947-04-06"] <- spring
    dst[dates == "1947-10-05"] <- autumn
    dst[dates == "1948-04-18"] <- spring
    dst[dates == "1948-10-03"] <- autumn
    dst[dates == "1949-04-06"] <- spring
    dst[dates == "1949-10-02"] <- autumn
    dst[dates == "1980-04-06"] <- spring
    dst[dates == "1980-09-28"] <- autumn
    dst[weekDay == 0 & monthDay > 24 & month == 3 & year > 1980] <- spring
    dst[weekDay == 0 & monthDay > 24 & month == 10 & year > 1995] <- autumn
    dst[weekDay == 0 & monthDay > 23 & month == 9 & year > 1980 & 
        year < 1996] <- autumn
    return(dst)
}

### Centering regressors
### Author: Daniel Ollech
center_regressor <- function (x) {
    classX <- class(x)[1]
    if (!classX %in% c("ts", "mts", "xts")) {
        stop("x must be a 'ts-', 'mts-' or 'xts-object'!")
    }
    else if (classX == "ts" | classX == "mts") {
        x <- xts::as.xts(x)
    }
    .substr_from <- function(x) {
        dates <- as.character(zoo::index(x))
        return(substr(dates, 6, nchar(dates)))
    }
    yearless_dates <- .substr_from(x)
    Means <- stats::aggregate(x = x, by = yearless_dates, FUN = mean, 
        na.rm = TRUE)
    .subs <- function(y, Means) {
        as.numeric(y) - as.numeric(Means[grep(.substr_from(y), 
            zoo::index(Means))])
    }
    out <- sapply(seq_len(nrow(x)), function(y) .subs(x[y], Means = Means))
    if (is.matrix(out)) {
        out <- t(out)
    }
    out <- xts::xts(out, zoo::index(x))
    colnames(out) <- colnames(x)
    if (classX == "ts" | classX == "mts") {
        out <- stats::as.ts(out)
    }
    return(out)
}

### Creating interaction regressors
### Author: Daniel Ollech
cross_seasonal <- function (reference = "12-24", span = 14, Day = c("0"), output = "xts", 
    y = NULL, from = "2000", to = "2030") {
    if (is.null(y)) {
        dates <- seq(as.Date(paste0(as.character(from), "-01-01")), 
            as.Date(paste0(as.character(to), "-12-31")), by = "days")
        y <- xts::xts(rep(0, length(dates)), order.by = dates)
    }
    time <- seq.Date(from = as.Date(utils::head(zoo::index(y), 
        1)), to = as.Date(utils::tail(zoo::index(y), 1)), by = "days")
    seriesA <- xts::xts(rep(0, length(time)), time)
    for (j in Day) {
        seriesA[format(zoo::index(seriesA), "%w") == j] <- 1
    }
    seriesB <- xts::xts(rep(0, length(time)), time)
    timespan <- format(seq.Date(as.Date(paste0("2015-", reference)), 
        by = "days", length.out = span), "%m-%d")
    seriesB[format(zoo::index(seriesB), "%m-%d") %in% timespan] <- 1
    series <- seriesA * seriesB
    
        out <- series

    return(out)
}

### Add to time series together filling up missing with 0
### Author: Daniel Ollech
.add <- function (x, y, ...) {
    x[is.na(x)] <- 0
    y[is.na(y)] <- 0
    dots <- list(...)
    for (j in dots) {
        a <- j
        a[is.na(a)] <- 0
        x <- x + a
    }
    return(x + y)
}



```




```{r}

# Base regressor
dates <- seq(as.Date("1950-01-01"), as.Date("2100-12-31"), by = "days")
Base  <- xts::xts(rep(0, length(dates)), order.by = dates)

### Nation wide

# New Years
NewYearsEve <- NewYearsDay <- Base
NewYearsEve[as.Date(timeDate::NewYearsDay(1950:2100)) - 1] <- 1
NewYearsEve[length(NewYearsEve)] <- 1
NewYearsDay[as.Date(timeDate::NewYearsDay(1950:2100))] <- 1

# Easter related
GoodFriday <- EasterSunday <- EasterMonday <- Base
GoodFriday[as.Date(timeDate::GoodFriday(1950:2100))] <- 1
EasterSunday[as.Date(timeDate::EasterSunday(1950:2100))] <- 1
EasterMonday[as.Date(timeDate::EasterMonday(1950:2100))] <- 1
HolySaturday <- lag0(EasterSunday,-1)
HolyThursday <- lag0(EasterSunday,-3)
EasterMondayAft1Day <- lag0(EasterMonday, 1)

# CarnivalMonday and Mardi Gras
CarnivalMonday <- lag0(EasterSunday,-48)
MardiGras <- lag0(EasterSunday,-47)

# German Labour Day
LabourDay <- Base
LabourDay[as.Date(timeDate::LaborDay(1950:2100))] <- 1

# US Labour Day
USLabourDay <- Base
USLabourDay[as.Date(timeDate::USLaborDay(1950:2100))] <- 1

# Ascension
Ascension <- Base
Ascension[as.Date(timeDate::Ascension(1950:2100))] <- 1
AscensionBef1Day <- lag0(Ascension,-1)
AscensionAft1Day <- lag0(Ascension, 1)

# Pentecost
Pentecost <- PentecostMonday <- Base
Pentecost[as.Date(timeDate::Pentecost(1950:2100))] <- 1
PentecostMonday[as.Date(timeDate::PentecostMonday(1950:2100))] <- 1
PentecostAft1Day <- lag0(PentecostMonday, 1)
PentecostBef1Day <- lag0(Pentecost,-1)

# German Unity
GermanUnity <- Base
GermanUnity[as.Date(timeDate::DEGermanUnity(1950:2100))] <- 1

# Christmas
ChristmasEve <- ChristmasDay <- BoxingDay <- Base
ChristmasEve[as.Date(timeDate::ChristmasEve(1950:2100))] <- 1
ChristmasDay[as.Date(timeDate::ChristmasDay(1950:2100))] <- 1
BoxingDay[as.Date(timeDate::BoxingDay(1950:2100))] <- 1

# Reformation Day (Martin Luther)
ReformationDay2017 <- ReformationDay <- Base
ReformationDay2017["2017-10-31"] <- 1

ReformationDay[format(zoo::index(ReformationDay), "%m-%d") == "10-31"] <-
  1

### Regional holidays

# Epiphany (BW, BY, ST)
Epiphany <- Base
Epiphany[as.Date(timeDate::Epiphany(1950:2100))] <- 1


# Corpus Christi (BW, BY, HE, NW, RP, SL)
CorpusChristi <- Base
CorpusChristi[as.Date(timeDate::DECorpusChristi(1950:2100))] <- 1
CorpusChristiAft1Day <- lag0(CorpusChristi)
CorpusChristiBef1Day <- lag0(CorpusChristi,-1)

# Assumption of Mary (BY, SL)
AssumptionOfMary <- Base
AssumptionOfMary[as.Date(timeDate::AssumptionOfMary(1950:2100))] <-
  1


# All Saints (BW, BY, NW, RP, SL)
AllSaints <- Base
AllSaints[as.Date(timeDate::AllSaints(1950:2100))] <- 1



# Cross-Seasonal Effects
PreXmasSun3d <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = 3,
    Day = c("0"),
    output = "xts"
  ) # Sunday in the days before Christmas
PreXmasSat3d <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = 3,
    Day = c("6"),
    output = "xts"
  ) # 

PostXmasSun1w <-
  cross_seasonal(
    y = Base,
    reference = "12-27",
    span = 7,
    Day = c("0"),
    output = "xts"
  ) # Sunday in the week after Christmas
PostXmasSat1w <-
  cross_seasonal(
    y = Base,
    reference = "12-27",
    span = 7,
    Day = c("6"),
    output = "xts"
  )  
PostXmasSun10d <-
  cross_seasonal(
    y = Base,
    reference = "12-27",
    span = 10,
    Day = c("0"),
    output = "xts"
  ) # Sunday in the 10 days after Christmas
PostXmasSat10d <-
  cross_seasonal(
    y = Base,
    reference = "12-27",
    span = 10,
    Day = c("6"),
    output = "xts"
  )  
PostNewEveSun1w <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 7,
    Day = c("0"),
    output = "xts"
  ) # Sunday at or after New Years Eve
PostNewEveSat1w <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 7,
    Day = c("6"),
    output = "xts"
  ) # Sa in der zweiten Woche nach Weihnachten (inkl Silvester)


Aug15Sun <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Aug15Sat <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Aug15Fri <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Aug15Thu <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Aug15Wed <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Aug15Tue <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Aug15Mon <-
  cross_seasonal(
    y = Base,
    reference = "08-15",
    span = 1,
    Day = c("1"),
    output = "xts"
  )

May1Sun <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
May1Sat <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
May1Fri <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
May1Thu <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
May1Wed <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
May1Tue <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
May1Mon <-
  cross_seasonal(
    y = Base,
    reference = "05-01",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
May1Bridge <-
  .add(lag0(May1Tue,-1), lag0(May1Thu, 1))

Oct3Sun <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Oct3Sat <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Oct3Fri <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Oct3Thu <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Oct3Wed <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Oct3Tue <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Oct3Mon <-
  cross_seasonal(
    y = Base,
    reference = "10-03",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
Oct3Bridge <-
  .add(lag0(Oct3Tue,-1), lag0(Oct3Thu, 1))

Oct31Sun <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Oct31Sat <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Oct31Fri <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Oct31Thu <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Oct31Wed <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Oct31Tue <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Oct31Mon <-
  cross_seasonal(
    y = Base,
    reference = "10-31",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
Oct31Bridge <-
  .add(lag0(Oct31Tue,-1), lag0(Oct31Thu, 1))

Nov1Sun <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Nov1Sat <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Nov1Fri <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Nov1Thu <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Nov1Wed <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Nov1Tue <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Nov1Mon <-
  cross_seasonal(
    y = Base,
    reference = "11-01",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
Nov1Bridge <-
  .add(lag0(Nov1Tue,-1), lag0(Nov1Thu, 1))



periodlength <- as.Date("2020-01-05") - as.Date("2019-12-21") + 1
XmasPeriodSun <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("0"),
    output = "xts"
  ) # Alle Sonntage in den 16 Tage ab 21.12
Dec24Sun <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Dec25Sun <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Dec26Sun <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Dec24Sat <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Dec25Sat <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Dec26Sat <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Dec24Fri <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Dec25Fri <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Dec26Fri <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Dec24Thu <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Dec25Thu <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Dec26Thu <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Dec24Wed <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Dec25Wed <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Dec26Wed <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Dec24Tue <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Dec25Tue <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Dec26Tue <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Dec24Mon <-
  cross_seasonal(
    y = Base,
    reference = "12-24",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
Dec25Mon <-
  cross_seasonal(
    y = Base,
    reference = "12-25",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
Dec26Mon <-
  cross_seasonal(
    y = Base,
    reference = "12-26",
    span = 1,
    Day = c("1"),
    output = "xts"
  )
XmasPeriodMon <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("1"),
    output = "xts"
  )
XmasPeriodTue <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("2"),
    output = "xts"
  )
XmasPeriodWed <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("3"),
    output = "xts"
  )
XmasPeriodThu <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("4"),
    output = "xts"
  )
XmasPeriodFri <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("5"),
    output = "xts"
  )
XmasPeriodSat <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("6"),
    output = "xts"
  )
XmasPeriodSun <-
  cross_seasonal(
    y = Base,
    reference = "12-21",
    span = periodlength,
    Day = c("0"),
    output = "xts"
  )

Dec31Sun <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Dec31Sat <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Dec31Fri <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Dec31Thu <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Dec31Wed <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Dec31Tue <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Dec31Mon <-
  cross_seasonal(
    y = Base,
    reference = "12-31",
    span = 1,
    Day = c("1"),
    output = "xts"
  )

Jan1Sun <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Jan1Sat <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Jan1Fri <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Jan1Thu <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Jan1Wed <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Jan1Tue <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Jan1Mon <-
  cross_seasonal(
    y = Base,
    reference = "01-01",
    span = 1,
    Day = c("1"),
    output = "xts"
  )

Jan6Sun <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("0"),
    output = "xts"
  )
Jan6Sat <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("6"),
    output = "xts"
  )
Jan6Fri <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("5"),
    output = "xts"
  )
Jan6Thu <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("4"),
    output = "xts"
  )
Jan6Wed <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("3"),
    output = "xts"
  )
Jan6Tue <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("2"),
    output = "xts"
  )
Jan6Mon <-
  cross_seasonal(
    y = Base,
    reference = "01-06",
    span = 1,
    Day = c("1"),
    output = "xts"
  )



PentecostPeriod <-
  .add(lag0(PentecostMonday,-1),
             PentecostMonday,
             lag0(PentecostMonday, 1)) # A negative value will create a dummy before the holiday, a positive number after the holiday


EasterPeriod <-
  .add(
    lag0(EasterMonday,-4),
    lag0(EasterMonday,-3),
    lag0(EasterMonday,-2),
    lag0(EasterMonday,-1),
    EasterMonday,
    lag0(EasterMonday, 1)
  )

# Daylight Saving Time
DstSpring <- create_dst_regressor(Base, spring = 1, autumn = 0)
DstAutumn <- create_dst_regressor(Base, spring = 0, autumn = 1)
Dst <- create_dst_regressor(Base, spring = -1, autumn = 1)



# Saving
All <-
  merge(
    AllSaints,
    Ascension,
    AscensionAft1Day,
    AscensionBef1Day,
    AssumptionOfMary,
    Aug15Mon,
    Aug15Tue,
    Aug15Wed,
    Aug15Thu,
    Aug15Fri,
    Aug15Sat,
    Aug15Sun,
    Base,
    BoxingDay,
    CarnivalMonday,
    ChristmasDay,
    ChristmasEve,
    CorpusChristi,
    CorpusChristiAft1Day,
    CorpusChristiBef1Day,
    Dec24Mon,
    Dec24Tue,
    Dec24Wed,
    Dec24Thu,
    Dec24Fri,
    Dec24Sat,
    Dec24Sun,
    Dec25Mon,
    Dec25Tue,
    Dec25Wed,
    Dec25Thu,
    Dec25Fri,
    Dec25Sat,
    Dec25Sun,
    Dec26Mon,
    Dec26Tue,
    Dec26Wed,
    Dec26Thu,
    Dec26Fri,
    Dec26Sat,
    Dec26Sun,
    Dec31Mon,
    Dec31Tue,
    Dec31Wed,
    Dec31Thu,
    Dec31Fri,
    Dec31Sat,
    Dec31Sun,
    EasterMonday,
    EasterMondayAft1Day,
    EasterPeriod,
    EasterSunday,
    Epiphany,
    GermanUnity,
    GoodFriday,
    HolyThursday,
    HolySaturday,
    Jan1Mon,
    Jan1Tue,
    Jan1Wed,
    Jan1Thu,
    Jan1Fri,
    Jan1Sat,
    Jan1Sun,
    Jan6Mon,
    Jan6Tue,
    Jan6Wed,
    Jan6Thu,
    Jan6Fri,
    Jan6Sat,
    Jan6Sun,
    LabourDay,
    MardiGras,
    May1Mon,
    May1Tue,
    May1Wed,
    May1Thu,
    May1Fri,
    May1Sat,
    May1Sun,
    May1Bridge,
    NewYearsDay,
    NewYearsEve,
    Nov1Mon,
    Nov1Tue,
    Nov1Wed,
    Nov1Thu,
    Nov1Fri,
    Nov1Sat,
    Nov1Sun,
    Nov1Bridge,
    Oct3Mon,
    Oct3Tue,
    Oct3Wed,
    Oct3Thu,
    Oct3Fri,
    Oct3Sat,
    Oct3Sun,
    Oct3Bridge,
    Oct31Mon,
    Oct31Tue,
    Oct31Wed,
    Oct31Thu,
    Oct31Fri,
    Oct31Sat,
    Oct31Sun,
    Oct31Bridge,
    Pentecost,
    PentecostAft1Day,
    PentecostBef1Day,
    PentecostMonday,
    PentecostPeriod,
    PostNewEveSat1w,
    PostNewEveSun1w,
    PostXmasSat1w,
    PostXmasSun1w,
    PostXmasSat10d,
    PostXmasSun10d,
    PreXmasSat3d,
    PreXmasSun3d,
    ReformationDay,
    ReformationDay2017,
    XmasPeriodMon,
    XmasPeriodTue,
    XmasPeriodWed,
    XmasPeriodThu,
    XmasPeriodFri,
    XmasPeriodSat,
    XmasPeriodSun,
    DstSpring,
    DstAutumn,
    USLabourDay
  )

holidays <- All
#saveRDS(holidays, file = "holidays.rds")  # Saving out the holiday regressors


# holidaysCentered <- center_regressor(All) # NOT RUN HERE, TAKES QUITE SOME TIME
# saveRDS(holidaysCentered, file = "holidaysCentered.rds")  # Saving out the centered regressors


```

